Feature/app bundle
retest/bundles pull request #2
Opened 2019-12-17 16:14 UTC by kema91

2019-12-21 17:08 UTC, martin-v requested changes

2019-12-21 17:08 UTC, martin-v commented on ci/script.sh
> +    BUCKET='DO:retest'
Obsolete, or?

2019-12-21 17:08 UTC, martin-v commented on ci/script.sh
> +    BUCKET='DO:retest'
Obsolete, or?

2019-12-27 14:31 UTC, kema91 commented on ci/script.sh
> +    BUCKET='DO:retest'
good catch, was a survival from my test setup

2020-01-09 13:11 UTC, martin-v approved these changes

2020-01-09 13:13 UTC, merged